//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int idClient { get; set; }
        public int idPriceList { get; set; }
        public int idModel { get; set; }
        public int idStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Model Model { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Status Status { get; set; }
    }
}
